name: CrazyAuctionsReloaded
authors:
- BadBones69
- TRCRedstoner
- BingYanchi
- MrXiaoM
main: top.mrxiaom.crazyauctions.reloaded.Main
version: ${version}
api-version: 1.13
description: Reloaded version of CrazyAuctionsPlus plugin. The original author was TRCStudioDean (TRC Studio & PA Project) and BadBones69.
depend:
  - Vault
softdepend:
  - PlaceholderAPI
  - LangUtils
commands:
    ca:
        description: Crazy Auctions Plus Main command.
        aliases: [car, crazyauction, crazyauctions, crazyauctionsreloaded, market]
